name: CI
on: [pull_request]
jobs:
  build:
    name: Build, lint, test, and check size
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install deps
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --immutable

      - name: Lint
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint

      - name: Test
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test --ci --coverage --maxWorkers=2

      - name: Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Check size
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: size
